version: '3.1'

services:
  app:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      MONGO_HOSTNAME: mongo
    depends_on:
      - mongo
    restart: on-failure
    entrypoint: sh -c "node index.js"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/